### ISSUE TITLE
Unclear README

### ISSUE THREAD

**Issue by uPaymeiFixit** [trung/InMemoryJavaCompiler#1]
The README for this project does not explain how to properly take advantage of this project. It looks great, but I'm not sure where to start. It looks like there is a working example included, but I don't see how to use it. 

Do you have any example code you could put on the README to show users how to utilize the InMemoryJavaCompiler class?

**Comment by trung** [comment]
Thanks for the feedback and sorry for the delay.
Sample code is given in the README itself but what missing is the maven dependency even though the code base is pretty small to clone and compile yourself. And I've updated the README with some more basic information. 
Regarding the usage, I've not used it in any real project. But I've received emails from number of folks using it in theirs.
