### ISSUE TITLE
NullPointerException on any use

### ISSUE THREAD

**Issue by NonameSLdev** [trung/InMemoryJavaCompiler#11]
Hey, I'm getting a NullPointerException whenever I try to use the compiler. I tried it with your example:

```
StringBuffer sourceCode = new StringBuffer();
sourceCode.append("package org.mdkt;\n");
sourceCode.append("public class HelloClass {\n");
sourceCode.append("   public String hello() { return \"hello\"; }");
sourceCode.append("}");

try{
        Class<?> helloClass = InMemoryJavaCompiler.compile("org.mdkt.HelloClass", sourceCode.toString()); // <--- Line 16
    }catch(Exception e){
        e.printStackTrace();
    }

```

And it doesn't work. The exception:

```
java.lang.NullPointerException
    at org.mdkt.compiler.InMemoryJavaCompiler.compile(InMemoryJavaCompiler.java:19)
    at me.nonamesldev.javacompilerexample.JavaCompilerExample.main(JavaCompilerExample.java:16)
```

I tried it with different source codes, all don't work.

**Comment by NonameSLdev** [comment]
After a little debugging, I found out that in the InMemoryJavaCompiler class, javac is null for a reason - I didn't have JDK installed. Silly me :P Add a note in the readme.md that you need JDK tho :)

**Comment by shivam92** [comment]
I have installed JDK, even I am getting NullPointerException.When I debug I got javac is null.
I configure the application in eclipse.

static JavaCompiler javac = ToolProvider.getSystemJavaCompiler();
is not able to create instance of javac
If any idea please provide me.

**Comment by trung** [comment]
Related to https://github.com/trung/InMemoryJavaCompiler/issues/12
