### ISSUE TITLE
Intercepting the error stream

### ISSUE THREAD

**Issue by ArsenArsen** [trung/InMemoryJavaCompiler#9]
Hello!
This is more a question, but is it possible to intercept the compile errors and get them in a stream or string?
I am making myself an app that uses this compiler and I want it to be able to show compile errors.
Thanks in advance.

**Comment by trung** [comment]
There's a pull request for this: https://github.com/trung/InMemoryJavaCompiler/pull/5 I'll work out with the contributor and make it available

**Comment by trung** [comment]
It's now available in master
